name: 'Github Action for the Zeet CLI'
description: 'Automatically loads the Zeet CLI into your Actions environment'
inputs:
  token:
    description: 'Zeet API Token (from https://zeet.co/account/api)'
    required: true
  api_url:
    description: "Zeet API URL"
    required: false
    default: "https://anchor.zeet.co"
runs:
  using: 'node16'
  main: 'dist/index.js'
